---
    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Ensure Ansible runs on start
          cron:
            name: "Excute ansible on start"
            special_time: reboot
            job: "ansible-playbook /scripts/site.yaml"
    
    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      vars:
        pip_install_packages:
          - name: docker
      roles:
        - geerlingguy.docker
        - geerlingguy.pip

    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Docker compose up
          shell: |
            cd /scripts/docker-compose
            docker-compose up -d
