---
    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Ensure Ansible runs on start
          cron:
            name: "Excute ansible on start"
            special_time: reboot
            job: "ansible-playbook /scripts/site.yaml"
    
    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      vars:
        pip_install_packages:
          - name: docker
      roles:
        - geerlingguy.docker
        - geerlingguy.pip

    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Docker compose up
          shell: |
            rm -rf /docker-elk
            
    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Clone ELK repo
          git:
            repo: 'https://github.com/deviantony/docker-elk.git'
            dest: /docker-elk

    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Docker compose up
          shell: |
            cd /docker-elk
            sed -i 's#LS_JAVA_OPTS: "-Xmx256m -Xms256m"#LS_JAVA_OPTS: "-Xmx64m -Xms32m"#g' docker-compose.yml
            sed -i 's#5601:5601#80:5601#g' docker-compose.yml
            docker-compose up -d
