---
    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Ensure Ansible runs on start
          cron:
            name: "Excute ansible on start"
            special_time: reboot
            job: "ansible-playbook /site.yaml"
   
    # https://github.com/deviantony/docker-elk
    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      vars:
        filebeat_inputs:
            - type: log
              paths:
                - "/var/log/*.log"
              encoding: utf-8
            - type: docker
              containers.ids:
                - "*"
              json.keys_under_root: true
              json.add_error_key: true
        filebeat_output_logstash_enabled: false
        filebeat_output_elasticsearch_enabled: true
        filebeat_output_elasticsearch_hosts:
          - "ELK_IP:9200"
      roles:
        - geerlingguy.filebeat

    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Update configuration
          shell: |
            sed -i 's/#protocol: "https"/protocol: "http"/g' /etc/filebeat/filebeat.yml
            sed -i 's/#username: "admin"/username: "elastic"/g' /etc/filebeat/filebeat.yml
            sed -i 's/#password: "s3cr3t"/password: "changeme"/g' /etc/filebeat/filebeat.yml
            /etc/init.d/filebeat restart | cat

    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      vars:
        pip_install_packages:
          - name: docker
      roles:
        - geerlingguy.docker
        - geerlingguy.pip

    - hosts: localhost
      connection: local 
      become: yes
      become_user: root
      user: ubuntu
      tasks:
        - name: Clone ELK repo
          git:
            repo: 'https://github.com/davisliu11/jrcms.git'
            dest: /jrcms

    - hosts: localhost
      connection: local 
      become: yes
      user: ubuntu
      tasks:
        - name: Start jrcms container
          shell: docker-compose -f /jrcms/docker-compose.yaml up
    

